package obligatorio2parking;

import javax.swing.JOptionPane;

public class VentanaSistema extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public VentanaSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClaroOscuro = new javax.swing.JButton();
        jMenuPrincipal = new javax.swing.JMenuBar();
        menuGestion = new javax.swing.JMenu();
        itemGestionClientes = new javax.swing.JMenuItem();
        itemVehiculos = new javax.swing.JMenuItem();
        itemEmpleados = new javax.swing.JMenuItem();
        itemContratos = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        itemEntradas = new javax.swing.JMenuItem();
        itemSalidas = new javax.swing.JMenuItem();
        itemServicios = new javax.swing.JMenuItem();
        menuVarios = new javax.swing.JMenu();
        itemReportes = new javax.swing.JMenuItem();
        itemRecupDatos = new javax.swing.JMenuItem();
        itemGrabDatos = new javax.swing.JMenuItem();
        itemMiniJuego = new javax.swing.JMenuItem();
        itemInfoAutores = new javax.swing.JMenuItem();
        menuTerminar = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obligatorio Prog 2 - Autores: Estudiantes: Jhonatan Adalid (320368) y Lorenzo Aldao ()");

        btnClaroOscuro.setText("Claro/Oscuro");

        menuGestion.setText("Gestión");

        itemGestionClientes.setText("Gestion de Clientes");
        itemGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionClientesActionPerformed(evt);
            }
        });
        menuGestion.add(itemGestionClientes);

        itemVehiculos.setText("Gestion de Vehículos");
        itemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVehiculosActionPerformed(evt);
            }
        });
        menuGestion.add(itemVehiculos);

        itemEmpleados.setText("Gestion de Empleados");
        itemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadosActionPerformed(evt);
            }
        });
        menuGestion.add(itemEmpleados);

        itemContratos.setText("Gestion de Contratos");
        itemContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemContratosActionPerformed(evt);
            }
        });
        menuGestion.add(itemContratos);

        jMenuPrincipal.add(menuGestion);

        menuMovimientos.setText("Movimientos");

        itemEntradas.setText("Entradas");
        itemEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEntradasActionPerformed(evt);
            }
        });
        menuMovimientos.add(itemEntradas);

        itemSalidas.setText("Salidas");
        itemSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalidasActionPerformed(evt);
            }
        });
        menuMovimientos.add(itemSalidas);

        itemServicios.setText("Servicios Adicionales");
        itemServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemServiciosActionPerformed(evt);
            }
        });
        menuMovimientos.add(itemServicios);

        jMenuPrincipal.add(menuMovimientos);

        menuVarios.setText("Varios");

        itemReportes.setText("Reportes");
        itemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportesActionPerformed(evt);
            }
        });
        menuVarios.add(itemReportes);

        itemRecupDatos.setText("Recuperación de datos");
        itemRecupDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecupDatosActionPerformed(evt);
            }
        });
        menuVarios.add(itemRecupDatos);

        itemGrabDatos.setText("Grabación de datos");
        itemGrabDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGrabDatosActionPerformed(evt);
            }
        });
        menuVarios.add(itemGrabDatos);

        itemMiniJuego.setText("MiniJuego");
        itemMiniJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMiniJuegoActionPerformed(evt);
            }
        });
        menuVarios.add(itemMiniJuego);

        itemInfoAutores.setText("Información de Autores");
        itemInfoAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoAutoresActionPerformed(evt);
            }
        });
        menuVarios.add(itemInfoAutores);

        jMenuPrincipal.add(menuVarios);

        menuTerminar.setText("Terminar");
        menuTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTerminarActionPerformed(evt);
            }
        });

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuTerminar.add(itemSalir);

        jMenuPrincipal.add(menuTerminar);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnClaroOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(btnClaroOscuro)
                .addGap(67, 67, 67))
        );

        setBounds(0, 0, 576, 324);
    }// </editor-fold>//GEN-END:initComponents

    private void itemGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionClientesActionPerformed
        VentanaClientes vc = new VentanaClientes();
        vc.setVisible(true);
    }//GEN-LAST:event_itemGestionClientesActionPerformed

    private void itemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVehiculosActionPerformed
        VentanaVehiculos vv = new VentanaVehiculos();
        vv.setVisible(true);
    }//GEN-LAST:event_itemVehiculosActionPerformed

    private void itemSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalidasActionPerformed
        VentanaSalidas vs = new VentanaSalidas();
        vs.setVisible(true);
    }//GEN-LAST:event_itemSalidasActionPerformed

    private void itemMiniJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMiniJuegoActionPerformed
        VentanaMiniJuego vm = new VentanaMiniJuego();
        vm.setVisible(true);
    }//GEN-LAST:event_itemMiniJuegoActionPerformed

    private void menuTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTerminarActionPerformed
        
    }//GEN-LAST:event_menuTerminarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro que querés salir del sistema?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntradasActionPerformed
        VentanaEntradas ve = new VentanaEntradas();
        ve.setVisible(true);
    }//GEN-LAST:event_itemEntradasActionPerformed

    private void itemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadosActionPerformed
        VentanaEmpleados ve = new VentanaEmpleados();
        ve.setVisible(true);
    }//GEN-LAST:event_itemEmpleadosActionPerformed

    private void itemContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContratosActionPerformed
        VentanaContratos vc = new VentanaContratos();
        vc.setVisible(true);
    }//GEN-LAST:event_itemContratosActionPerformed

    private void itemServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemServiciosActionPerformed
        VentanaServiciosAdicionales vsa = new VentanaServiciosAdicionales();
        vsa.setVisible(true);
    }//GEN-LAST:event_itemServiciosActionPerformed

    private void itemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportesActionPerformed
        VentanaReportes vr = new VentanaReportes();
        vr.setVisible(true);
    }//GEN-LAST:event_itemReportesActionPerformed

    private void itemRecupDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecupDatosActionPerformed
        VentanaRecuperarDatos vrd = new VentanaRecuperarDatos();
        vrd.setVisible(true);
    }//GEN-LAST:event_itemRecupDatosActionPerformed

    private void itemGrabDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGrabDatosActionPerformed
        VentanaGrabarDatos vgd = new VentanaGrabarDatos();
        vgd.setVisible(true);
    }//GEN-LAST:event_itemGrabDatosActionPerformed

    private void itemInfoAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoAutoresActionPerformed
        VentanaAutores via = new VentanaAutores();
        via.setVisible(true);
    }//GEN-LAST:event_itemInfoAutoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaroOscuro;
    private javax.swing.JMenuItem itemContratos;
    private javax.swing.JMenuItem itemEmpleados;
    private javax.swing.JMenuItem itemEntradas;
    private javax.swing.JMenuItem itemGestionClientes;
    private javax.swing.JMenuItem itemGrabDatos;
    private javax.swing.JMenuItem itemInfoAutores;
    private javax.swing.JMenuItem itemMiniJuego;
    private javax.swing.JMenuItem itemRecupDatos;
    private javax.swing.JMenuItem itemReportes;
    private javax.swing.JMenuItem itemSalidas;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemServicios;
    private javax.swing.JMenuItem itemVehiculos;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuTerminar;
    private javax.swing.JMenu menuVarios;
    // End of variables declaration//GEN-END:variables
}
