package obligatorio2parking;

import javax.swing.JOptionPane;

public class VentanaSistema extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public VentanaSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClaroOscuro = new javax.swing.JButton();
        jMenuPrincipal = new javax.swing.JMenuBar();
        menuGestion = new javax.swing.JMenu();
        itemGestionClientes = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        itemEntradas = new javax.swing.JMenuItem();
        itemSalidas = new javax.swing.JMenuItem();
        itemServicios = new javax.swing.JMenuItem();
        menuVarios = new javax.swing.JMenu();
        itemReportes = new javax.swing.JMenuItem();
        itemRecupDatos = new javax.swing.JMenuItem();
        itemGrabDatos = new javax.swing.JMenuItem();
        itemMiniJuego = new javax.swing.JMenuItem();
        itemInfoAutores = new javax.swing.JMenuItem();
        menuTerminar = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Obligatorio Prog 2 - Autores: Estudiantes: Jhonatan Adalid (320368) y Lorenzo Aldao ()");

        btnClaroOscuro.setText("Claro/Oscuro");

        menuGestion.setText("Gestión");

        itemGestionClientes.setText("Gestion de Clientes");
        itemGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionClientesActionPerformed(evt);
            }
        });
        menuGestion.add(itemGestionClientes);

        jMenuItem1.setText("Gestion de Vehículos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuGestion.add(jMenuItem1);

        jMenuItem2.setText("Gestion de Empleados");
        menuGestion.add(jMenuItem2);

        jMenuItem3.setText("Gestion de Contratos");
        menuGestion.add(jMenuItem3);

        jMenuPrincipal.add(menuGestion);

        menuMovimientos.setText("Movimientos");

        itemEntradas.setText("Entradas");
        menuMovimientos.add(itemEntradas);

        itemSalidas.setText("Salidas");
        itemSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalidasActionPerformed(evt);
            }
        });
        menuMovimientos.add(itemSalidas);

        itemServicios.setText("Servicios Adicionales");
        menuMovimientos.add(itemServicios);

        jMenuPrincipal.add(menuMovimientos);

        menuVarios.setText("Varios");

        itemReportes.setText("Reportes");
        menuVarios.add(itemReportes);

        itemRecupDatos.setText("Recuperación de datos");
        menuVarios.add(itemRecupDatos);

        itemGrabDatos.setText("Grabación de datos");
        menuVarios.add(itemGrabDatos);

        itemMiniJuego.setText("MiniJuego");
        itemMiniJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMiniJuegoActionPerformed(evt);
            }
        });
        menuVarios.add(itemMiniJuego);

        itemInfoAutores.setText("Información de Autores");
        menuVarios.add(itemInfoAutores);

        jMenuPrincipal.add(menuVarios);

        menuTerminar.setText("Terminar");
        menuTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTerminarActionPerformed(evt);
            }
        });

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuTerminar.add(itemSalir);

        jMenuPrincipal.add(menuTerminar);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnClaroOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(btnClaroOscuro)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionClientesActionPerformed
        VentanaClientes vc = new VentanaClientes();
        vc.setVisible(true);
    }//GEN-LAST:event_itemGestionClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSalidasActionPerformed

    private void itemMiniJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMiniJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMiniJuegoActionPerformed

    private void menuTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTerminarActionPerformed
        
    }//GEN-LAST:event_menuTerminarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro que querés salir del sistema?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaroOscuro;
    private javax.swing.JMenuItem itemEntradas;
    private javax.swing.JMenuItem itemGestionClientes;
    private javax.swing.JMenuItem itemGrabDatos;
    private javax.swing.JMenuItem itemInfoAutores;
    private javax.swing.JMenuItem itemMiniJuego;
    private javax.swing.JMenuItem itemRecupDatos;
    private javax.swing.JMenuItem itemReportes;
    private javax.swing.JMenuItem itemSalidas;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemServicios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuTerminar;
    private javax.swing.JMenu menuVarios;
    // End of variables declaration//GEN-END:variables
}
